<?php

// This file has been auto-generated by the Symfony Dependency Injection Component
// You can reference it in the "opcache.preload" php.ini setting on PHP >= 7.4 when preloading is desired

use Symfony\Component\DependencyInjection\Dumper\Preloader;

if (in_array(PHP_SAPI, ['cli', 'phpdbg'], true)) {
    return;
}

require dirname(__DIR__, 3).'/vendor/autoload.php';
(require __DIR__.'/Pure_PurewareCli_PureKernelDevDebugContainer.php')->set(\ContainerXEWPRiV\Pure_PurewareCli_PureKernelDevDebugContainer::class, null);
require __DIR__.'/ContainerXEWPRiV/getApplicationService.php';

$classes = [];
$classes[] = 'Symfony\Component\Console\Application';
$classes[] = 'Pure\PurewareCli\Command\Entity\MakeEntityCommand';
$classes[] = 'Symfony\Component\DependencyInjection\ContainerInterface';

$preloaded = Preloader::preload($classes);
