<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXEWPRiV\Pure_PurewareCli_PureKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXEWPRiV/Pure_PurewareCli_PureKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXEWPRiV.legacy');

    return;
}

if (!\class_exists(Pure_PurewareCli_PureKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXEWPRiV\Pure_PurewareCli_PureKernelDevDebugContainer::class, Pure_PurewareCli_PureKernelDevDebugContainer::class, false);
}

return new \ContainerXEWPRiV\Pure_PurewareCli_PureKernelDevDebugContainer([
    'container.build_hash' => 'XEWPRiV',
    'container.build_id' => 'a48f2e0b',
    'container.build_time' => 1666261590,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXEWPRiV');
